config/routes.rb
Pointup::Application.routes.draw do

  resources :projects, :only => [ :index, :show] do 
    resources :lists,  :only => [ :index, :show ] do 
      resources :todos, :only => [:index, :show, :edit, :update ] 
    end 
  end 

  get  "/basecamp/sync" => "basecamp#sync"
  post "/basecamp/sync" => "basecamp#update"

  get "/credentials" => "credentials#edit",   :as => :credentials
  put "/credentials" => "credentials#update", :as => :credentials
  
  get "/settings" => "settings#edit", :as => :settings
  put "/settings" => "settings#update", :as => :settings


  resources :users, :only => [:index, :destroy] do 
    member do 
      put 'authorize'
    end 
  end 
  get 'waiting' => 'users#waiting', :as => :waiting

  #github authorization routes 
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout 
  match "/signin"  => "sessions#new", :as => :signin

  match "home/index" => "home#index"
  #root 
  #root :to => 'home#index'
  root :to => 'projects#index'
end 

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :project
  has_many   :todos,  :dependent => :destroy

 def sync!(data)
    if  self.name != data.name
      self.name = data.name 
      save 
    end 
  end 

  def self.create_from_basecamp(data,project)
    create! do |l|
      l.project = project
      l.basecamp_id = data.id 
      l.name = data.name 
    end 
  end 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!


  # GET /lists
  # GET /lists.json
  def index
    @lists = current_project.lists

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = current_project.lists.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

private 
  def current_project 
    current_user.projects.find(params[:project_id])
  end 
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.haml
= simple_form_for(@list) do |f|
  = f.error_notification

  .inputs
    = f.input :name
    = f.input :basecamp_id
    = f.association :project

  .actions
    = f.button :submit

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
%h1 Listing lists

%table
  %tr
    %th Name
    %th Basecamp
    %th Project
    %th
    %th
    %th

  - @lists.each do |list|
    %tr
      %td= list.name
      %td= list.basecamp_id
      %td= list.project
      %td= link_to 'Show', list
      %td= link_to 'Edit', edit_list_path(list)
      %td= link_to 'Destroy', list, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New List', new_list_path

app/views/lists/new.html.haml
%h1 New list

= render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @list.name
%p
  %b Basecamp:
  = @list.basecamp_id
%p
  %b Project:
  = @list.project

= link_to 'Edit', edit_list_path(@list)
\|
= link_to 'Back', lists_path