config/routes.rb
Pointup::Application.routes.draw do

  resources :projects, :only => [ :index, :show] do 
    resources :lists,  :only => [ :index, :show ] do 
      resources :todos, :only => [:index, :show, :edit, :update ] 
    end 
  end 

  get  "/basecamp/sync" => "basecamp#sync"
  post "/basecamp/sync" => "basecamp#update"

  get "/credentials" => "credentials#edit",   :as => :credentials
  put "/credentials" => "credentials#update", :as => :credentials
  
  get "/settings" => "settings#edit", :as => :settings
  put "/settings" => "settings#update", :as => :settings


  resources :users, :only => [:index, :destroy] do 
    member do 
      put 'authorize'
    end 
  end 
  get 'waiting' => 'users#waiting', :as => :waiting

  #github authorization routes 
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout 
  match "/signin"  => "sessions#new", :as => :signin

  match "home/index" => "home#index"
  #root 
  #root :to => 'home#index'
  root :to => 'projects#index'
end 

app/models/user.rb
class User < ActiveRecord::Base
  attr_protected :admin
  before_create :set_admin
  has_many :projects, :dependent => :destroy

  def credentials?
    !self.basecamp_token.blank? or (!self.basecamp_login.blank? and !self.basecamp_password.blank?)
  end 

  def self.first?
    count == 0 
  end 
  def self.create_with_omniauth(auth)
    create! do |user|
      user.uid = auth["uid"]
      user.nickname = auth["info"]["nickname"]
    end
  end
private 
  def set_admin
    self.admin = User.first?
    true 
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_admin!
  def waiting
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  #PUT /users/1/authorize 
  def authorize
    @user = User.find(params[:id])
    @user.authorized = true 

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url }
        format.json { head :ok }
      else 
        format.html { render action: "index" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end 
    end
  end 

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .inputs

  .actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th User 
    %th Status
    %th 

  - @users.each do |user|
    %tr
      %td= user.nickname
      - if !user.authorized?
        %td= link_to 'Authorize', authorize_user_path(user), :confirm => 'Are you user?', :remote => true, :method => :put, :class => 'authorize-link'
      - else 
        %td X
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :remote => true, :method => :delete, :class => 'delete-link' 

:javascript
  $('body').delegate('.delete-link', 'ajax:success', function() {
    $(this).parents('tr').hide();
    alert('User successfully deleted.');
  })
  $('body').delegate('.delete-link', 'ajax:failure', function() {
    alert('There was an issue deleting the user');
  })

  $('body').delegate('.authorize-link', 'ajax:success', function() {
    $(this).parents('td').text('X');
    alert('User successfully authorized');
  })

  $('body').delegate('.authorize-link', 'ajax:failure', function() {
    alert('There was an issue deleting the user');
  })

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/users/waiting.html.haml
%h2.big Waiting for authorization for your admin

%br
%p Once your admin grants you authoriaztion, try going to the #{link_to "Home Page", root_path} again.
%br

app/views/users/wating.html.haml
%h1 User#wating
%p Find me in app/views/user/wating.html.haml