config/routes.rb
Pointup::Application.routes.draw do

  resources :projects, :only => [ :index, :show] do 
    resources :lists,  :only => [ :index, :show ] do 
      resources :todos, :only => [:index, :show, :edit, :update ] 
    end 
  end 

  get  "/basecamp/sync" => "basecamp#sync"
  post "/basecamp/sync" => "basecamp#update"

  get "/credentials" => "credentials#edit",   :as => :credentials
  put "/credentials" => "credentials#update", :as => :credentials
  
  get "/settings" => "settings#edit", :as => :settings
  put "/settings" => "settings#update", :as => :settings


  resources :users, :only => [:index, :destroy] do 
    member do 
      put 'authorize'
    end 
  end 
  get 'waiting' => 'users#waiting', :as => :waiting

  #github authorization routes 
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout 
  match "/signin"  => "sessions#new", :as => :signin

  match "home/index" => "home#index"
  #root 
  #root :to => 'home#index'
  root :to => 'projects#index'
end 

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  has_many :lists, :dependent => :destroy 

   def sync!(data)
    if  self.name != data.name
      self.name = data.name 
      save 
    end 
  end 

  def self.create_from_basecamp(data, user)
    create! do |p|
      p.user = user
      p.basecamp_id = data.id 
      p.name = data.name 
    end 
  end 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  .inputs
    = f.input :name
    = f.input :basecamp_id
    = f.association :user

  .actions
    = f.button :submit

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%br 

.grid_8
  #projects.container
    %p Loading...
.grid_8
  #lists.container
    %p please select a project 
%br
.clear 
%br
.grid_16
  #todos.container
    %p please select a list 



:javascript
  $(function() {
    // Blog is the app name
    window.todo_router = new Pointup.Routers.TodosRouter();
    window.list_router = new Pointup.Routers.ListsRouter();
    window.project_router = new Pointup.Routers.ProjectsRouter({ projects: #{@projects.to_json.html_safe} });
    Backbone.history.start();
    window.project_router.index();
  });

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @project.name
%p
  %b Basecamp:
  = @project.basecamp_id
%p
  %b User:
  = @project.user

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path